curso_adm/curso_adm/gerencia/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    # Curso
    url(r'^curso/list/$', 'curso_adm.gerencia.views.lista_cursos', name='curso_list'),
    url(r'^curso/form/$', 'curso_adm.gerencia.views.curso_form', name='curso_form'),
    url(r'^curso/form/(?P<pk>\d+)/$', 'curso_adm.gerencia.views.curso_form', name='curso_form'),
    url(r'^curso/delete/(?P<pk>\d+)/$', 'curso_adm.gerencia.views.curso_delete', name='curso_delete'),

    # Aluno
    url(r'^aluno/list/$', 'curso_adm.gerencia.views.lista_alunos', name='aluno_list'),
    url(r'^aluno/form/$', 'curso_adm.gerencia.views.aluno_form', name='aluno_form'),
    url(r'^aluno/form/(?P<pk>\d+)/$', 'curso_adm.gerencia.views.aluno_form', name='aluno_form'),
    # url(r'^aluno/delete/(?P<pk>\d+)/$', 'curso_adm.gerencia.views.aluno_delete', name='aluno_delete'),

    # Matricula
    url(r'^matricula/list/$', 'curso_adm.gerencia.views.lista_matriculas', name='matricula_list'),
    url(r'^matricula/form/$', 'curso_adm.gerencia.views.matricula_form', name='matricula_form'),
    url(r'^matricula/form/aluno:(?P<aluno_pk>\d+)/curso:(?P<curso_pk>\d+)/$', 'curso_adm.gerencia.views.matricula_form', name='matricula_form'),
    # url(r'^matricula/delete/(?P<pk>\d+)/$', 'curso_adm.gerencia.views.matricula_delete', name='matricula_delete')
)

curso_adm/curso_adm/urls.py
from django.conf.urls import include, patterns, url
from django.contrib.auth.views import logout, login

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'curso_adm.views.home', name='home'),

    url(r'^gerencia/', include('curso_adm.gerencia.urls')),

    url(r'^admin/', include(admin.site.urls)),

    # Logins
    url(r'^logout/$', logout, {"next_page": "/"}, name="logout"),
    url(r'^signin/$', login, {'template_name': 'login.html'}, name="login"),
)

curso_adm/curso_adm/gerencia/models.py
from django.db import models
from django.contrib.auth.models import User


class Curso(models.Model):
    nome = models.CharField(max_length=180, null=True, blank=False)

    def __unicode__(self):
        return self.nome or u''


class AlunoCurso(models.Model):
    curso = models.ForeignKey(Curso)
    aluno = models.ForeignKey(User)
    data = models.DateField(auto_now_add=True)


    def __unicode__(self):
        return u'%s: %s' % (self.aluno, self.curso)

curso_adm/curso_adm/gerencia/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Curso, AlunoCurso


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso


class AlunoCursoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super (AlunoCursoForm, self).__init__(*args, **kwargs)
        self.fields['aluno'].queryset = User.objects.exclude(is_superuser=True)

    class Meta:
        model = AlunoCurso

curso_adm/curso_adm/gerencia/views.py
# coding: utf-8
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect


from .forms import CursoForm, AlunoCursoForm
from .models import Curso, AlunoCurso

is_superuser = lambda user: user.is_superuser
is_not_superuser = lambda user: not is_superuser()



def lista_cursos(request):
    cursos = Curso.objects.all()
    return render(
        request,
        'gerencia/lista_cursos.html',
        {
            'lista_de_cursos': cursos
        }
    )


def aluno_form(request, pk=None):
    pass


@user_passes_test(is_superuser)
def lista_alunos(request):
    alunos = User.objects.filter(is_superuser=False)
    return render(
        request,
        'gerencia/lista_alunos.html',
        {
            'lista_de_alunos': alunos
        }
    )


@user_passes_test(is_superuser)
def aluno_info(request, pk):
    aluno = get_object_or_404(User, pk=pk)

    aluno_cursos = AlunoCurso.objects.filter(aluno=aluno)

    return render(
        request,
        'gerencia/aluno_cursos.html',
        {
            'aluno_cursos': aluno_cursos,
            'aluno': aluno,
        }
    )
    

@user_passes_test(is_superuser)
def curso_form(request, pk=None):
    if pk:
        curso = get_object_or_404(Curso, pk=pk)
    else:
        curso = Curso()

    form = CursoForm(request.POST or None, instance=curso)

    if request.method == 'POST':
        if form.is_valid():
            form.save()

        return redirect(reverse('curos_list'))

    return render(
        request,
        'gerencia/curso_form.html',
        {
            'form': form
        }
    )


@user_passes_test(is_superuser)
def curso_delete(request, pk):
    curso = get_object_or_404(Curso, pk=pk)
    curso.delete()
    return redirect(reverse('curos_list'))


@user_passes_test(is_superuser)
def lista_matriculas(request):
    matriculas = AlunoCurso.objects.all()
    return render(
        request,
        'gerencia/lista_matriculas.html',
        {
            'lista_de_matriculas': matriculas
        }
    )


# cria uma matricula selecionando Aluno e o curso
@user_passes_test(is_superuser)
def matricula_form(request, aluno_pk=None, curso_pk=None):
    if aluno_pk and curso_pk:
        aluno = get_object_or_404(User, pk=aluno_pk)
        curso = get_object_or_404(Curso, pk=curso_pk)
        alunocurso = get_object_or_404(AlunoCurso, aluno=aluno, curso=curso)
    else:
        aluno = User()
        curso = Curso()
        alunocurso = AlunoCurso()

    form = AlunoCursoForm(request.POST or None, instance=alunocurso)

    if request.method == 'POST':
        if form.is_valid():
            form.save()

            return redirect('/')

    return render(
        request,
        'gerencia/matricula_form.html',
        {
            'aluno': aluno,
            'curso': curso,
            'alunocurso': alunocurso,
            'form': form
        }
    )


# @user_passes_test(is_not_superuser)
# def aluno_matricula_form(request, curso_pk=None):

#     if curso_pk:
#         curso = get_object_or_404(Curso, pk=curso_pk)
#     else:
#         curso = Curso()

#     form = AlunoMatriculaCursoForm(request.POST or None, aluno=request.user, curso=curso)

curso_adm/curso_adm/views.py
from django.shortcuts import render


def home(request):
    
    return render(
        request,
        'index.html',
        {}
    )

curso_adm/curso_adm/gerencia/templates/gerencia/curso_form.html
{% extends "base.html" %}

{% block page_title %}
    {% if form.instance.pk %}
        {{ form.instance }}
    {% else %}
        Novo Curso
    {% endfor %}
{% endblock page_title %}

{% block content %}    
    <form action="POST">
        {{ form.as_p }}

        <input type="submit" value="Salvar">
    </form>
{% endblock content %}

curso_adm/curso_adm/gerencia/templates/gerencia/lista_alunos.html
{% extends "base.html" %}

{% block page_title %}
    Lista de Alunos
{% endblock page_title %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {% for aluno in lista_de_alunos %}
            <tr>
                <td><a href="{% url 'aluno_form' aluno.pk %}">{{ aluno.get_full_name }}</a></td>
                <td><a href="#" class="btn btn-danger btn-mini">Deletar</a></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">Quantidade de Alunos: {{ lista_de_alunos.count }}</td>
            </tr>
        </tfoot>
    </table>
{% endblock content %}

curso_adm/curso_adm/gerencia/templates/gerencia/lista_cursos.html
{% extends "base.html" %}

{% block page_title %}
    Lista de Cursos
{% endblock page_title %}

{% block content %}

    {% for curso in lista_de_cursos %}
        {{ curso }}
    {% endfor %}

{% endblock content %}

curso_adm/curso_adm/gerencia/templates/gerencia/lista_matriculas.html
{% extends "base.html" %}

{% block page_title %}
    Matrículas <a class="btn" href="{% url 'matricula_form' %}">Nova Matrícula</a>
{% endblock page_title %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>Aluno</th>
                <th>Curso</th>
                <th>Data</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {% for matricula in lista_de_matriculas %}
            <tr>
                <td>
                    <a href="{% url 'matricula_form' matricula.curso.pk matricula.aluno.pk %}">
                        {{ matricula.aluno.get_full_name }}
                    </a>
                </td>
                <td>{{ matricula.curso }}</td>
                <td>{{ matricula.data }}</td>
                <td><a href="#" class="btn btn-danger btn-mini">Deletar</a></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Quantidade de matrículas: {{ lista_de_matriculas.count }}</td>
            </tr>
        </tfoot>
    </table>
{% endblock content %}

curso_adm/curso_adm/gerencia/templates/gerencia/matricula_form.html
{% extends "base.html" %}

{% block page_title %}
    {% if form.instance.pk %}
        {{ form.instance }}
    {% else %}
        Nova Matrícula
    {% endif %}
{% endblock page_title %}

{% block content %}    
    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Salvar" class="btn">
    </form>
{% endblock content %}

curso_adm/curso_adm/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{{ project_name }}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to project.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><i class="icon-book icon-white" style="margin: 6px 0 0 0"></i> Cursos</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li id="id_home_navbar"><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
              {% if perms.auth.change_user %}
                <li id="id_user_navbar"><a href="#"><i class="icon-user icon-white"></i> Alunos</a></li>
              {% endif %}
              {% if perms.gerencia.change_curso %}
                <li id="id_curso_navbar"><a href="#"><i class="icon-tag icon-white"></i> Cursos</a></li>
              {% endif %}
              {% if perms.gerencia.change_alunocurso %}
                <li id="id_cargo_navbar"><a href="#"><i class="icon-inbox icon-white"></i> Matrículas</a></li>
              {% endif %}
            </ul>
            <ul class="nav pull-right">
              {% if not user.is_anonymous %}
                <li><a href="/logout/"><i class="icon-off icon-white"></i> Sair</a></li>
                <li id="id_perfil_navbar"><a href="/perfil/"><i class="icon-user icon-white"></i> Perfil</a></li>
              {% else %}
                <li id="id_signin_navbar"><a href="/signin"><i class="icon-lock icon-white"></i> Entrar</a></li>
                <li id="id_signup_navbar"><a href="/signup"><i class="icon-share-alt icon-white"></i> Cadastre-se</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <h1>{% block page_title %}Example Base Template{% endblock page_title %}</h1>

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

curso_adm/curso_adm/templates/confirm_delete.html
{% extends "base.html" %}
{% load bootstrap_toolkit %}

{% block page_title %}
    Deletar {{ object }}
{% endblock page_title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h4>Você tem certeza que deseja deletar "{{ object }}"?</h4>
        <input type="submit" value="Confirmar" class="btn btn-danger" />
    </form>
{% endblock content %}

curso_adm/curso_adm/templates/forgot_password.html
{% extends "base.html" %}
{% load bootstrap_toolkit %}

{% block page_title %}
    Esqueci Minha Senha
{% endblock page_title %}

{% block content %}
    <form method="post" action="{% url 'password_reset' %}">
        {% csrf_token %}
        <h4>
            Digite seu endereço de email.
        </h4>
        <h4>
            Você receberá um link para criar uma nova senha via e-mail.
        </h4>
        <input type="email" name="email" placeholder="seu e-mail"><br/>
        <button type="submit" class="btn btn-primary">Recuperar Senha</button>
    </form>
{% endblock content %}

curso_adm/curso_adm/templates/index.html
{% extends "base.html" %}

{% block page_title %}
    Gerenciador de Cursos
{% endblock page_title %}

{% block content %}

    AAA

{% endblock content %}

curso_adm/curso_adm/templates/login.html
{% extends "base.html" %}

{% block extra_css %}
<style type="text/css">
    body {
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        max-width: 250px;
        padding: 15px 20px 15px;
        margin: 10px auto;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        box-shadow: 0 1px 2px rgba(0,0,0,.05);
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin input[type="text"],
    .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
    }
    h1{
        max-width: 300px;
        padding: 5px 1px 1px 10px;
        margin: 10px auto;
    }
</style>
{% endblock extra_css %}

{% block page_title %}Login{% endblock page_title %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form class="form-signin" method="POST" action="{% if next %}?next={{ next }}{% endif %}">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-large btn-small btn-primary" type="submit">Login</button>
        
    </form>

{% endblock content %}